<?xml version="1.0"?>
<!DOCTYPE erabiltzailea [
<!ELEMENT erabiltzailea (eposta , izena , abizena1 , abizena2 , telefonoa)>
<!ELEMENT eposta (#PCDATA)>
<!ELEMENT izena (#PCDATA)>
<!ELEMENT abizena1 (#PCDATA)>
<!ELEMENT abizena2 (#PCDATA)>
<!ELEMENT telefonoa (#PCDATA)>
]>
<erabiltzaileak>
	<erabiltzailea>
		<eposta>jmperez001@ikasle.ehu.eus</eposta>
		<izena>Jon Mikel</izena>
		<abizena1>Perez</abizena1>
		<abizena2>Ledesma</abizena2>
		<telefonoa>634232323</telefonoa>
	</erabiltzailea>
	<erabiltzailea>
		<eposta>lalkorta@ikasle.ehu.eus</eposta>
		<izena>Luis</izena>
		<abizena1>Alkorta</abizena1>
		<abizena2>Bereziartua</abizena2>
		<telefonoa>634232324</telefonoa>
	</erabiltzailea>
	<erabiltzailea>
		<eposta>muribesalgo001@ikasle.ehu.eus</eposta>
		<izena>Maddi</izena>
		<abizena1>Uribesalgo</abizena1>
		<abizena2>Lopez de Arriortua</abizena2>
		<telefonoa>634232325</telefonoa>
    </erabiltzailea>
     <erabiltzailea>
        <eposta>xalonso001@ikasle.ehu.eus</eposta>
		<izena>Xabier</izena>
		<abizena1>Alonso</abizena1>
		<abizena2>Arrieta</abizena2>
		<telefonoa>696756463</telefonoa>
      </erabiltzailea>
	  <erabiltzailea>
        <eposta>gtoledo004@ikasle.ehu.es</eposta>
		<izena>Gorka</izena>
		<abizena1>Toledo</abizena1>
		<abizena2>Pellejero</abizena2>
		<telefonoa>123456789</telefonoa>
     </erabiltzailea>
	 <erabiltzailea>
        <eposta>jsigmund001@ikasle.ehu.es</eposta>
		<izena>Joziok</izena>
		<abizena1>Sigmund</abizena1>
		<abizena2>Freud</abizena2>
		<telefonoa>123456789</telefonoa>
      </erabiltzailea>
	  <erabiltzailea>
        <eposta>jalza004@ikasle.ehu.es</eposta>
		<izena>Joan</izena>
		<abizena1>Alza</abizena1>
		<abizena2>Santos</abizena2>
		<telefonoa>123456789</telefonoa>
      </erabiltzailea>
</erabiltzaileak>
